import sqlite3
import pandas as pd

# Read the CSV generated by parser
df = pd.read_csv("laser_output.csv")

# Create database (auto-created if not exists)
conn = sqlite3.connect("laser_data.db")

# Save data into table
df.to_sql(
    "laser_records",
    conn,
    if_exists="append",
    index=False
)

print(f"{len(df)} rows inserted successfully!")

conn.close()